"""
This code will take the events generated by the analyser and then produce snapshots to save in a fodler. 
"""

import av
import os
import cv2
from pathlib import Path
from src.analyse.event import Event

def snapshot_event_frames(video_path: str, events: list[Event], output_dir: Path = Path(__file__).parent.parent.parent / "data" / "output" / "frames"):
    """Takes the events and outputs the snapshots at the event start time"""

    os.makedirs(output_dir, exist_ok=True)

    container = av.open(video_path) #open the container

    #grab the video stream to get the time base to get seconds
    stream = container.streams.video[0] 
    time_base = float(stream.time_base)   

    event_timestamps = {} #events are now dicts in a list
    for i, event in enumerate(events): #cycle through the event list 
        ts = event.timestamp #get timestamp
        event_timestamps.setdefault(ts, []).append((i, event)) #accumulate timestamps and their corresponding events

    sorted_targets = sorted(event_timestamps.keys()) #sort by timestamp to make it a timeline
    target_idx = 0    #keep track of what event frame we are looking for in the stream

    #go through frames
    for frame in container.decode(stream):
        if target_idx >= len(sorted_targets): #want to make sure that we are only grabbing the number of frame needed
            break

        frame_ts = float(frame.pts * time_base) #get the time  of the current frame
        target_ts = sorted_targets[target_idx] #get the timestamp of the current event of interest

        if frame_ts >= target_ts: # due to possibility of the precision not being perfect, check if we are at or passed the frame of interest
            img = frame.to_ndarray(format="bgr24") 

            for event_i, event in event_timestamps[target_ts]: #iterate through the events in that frame 
                filename = f"{event_i:04d}_{event.event_type}_{target_ts:.1f}s.png" 
                cv2.imwrite(os.path.join(output_dir, filename), img)

            target_idx += 1 # go to the next timestamp

    container.close()
    print(f"Saved {target_idx} event frames to {output_dir}")

    return output_dir